### ISSUE TITLE
what is the recommended hyperparameter for Billiards dataset?

### ISSUE THREAD

**Issue by shansiliu95** [felixykliu/NAOMI#2]
I use the default hyperparameter to train on Billiards but the training is very unstable.

**Comment by yuqirose** [comment]
@felixykliu

**Comment by felixykliu** [comment]
Hi shansi,

Sorry for the late reply!  Busy with work recently and just saw the message...
The issue may not be related to the hyper-parameters, but rather the training scheme itself. So basically the sequence (200) is too long for the original problem, and there are too many missing values. So I would suggest starting from something easier (e.g. seq_length = 50, or less number of missing values, e.g. only 10% missing rate). Then when the model learnt to do the easier job, we can increase the number of missing values, and then we can have random number of missing values.

Hope that's helpful!

Thanks!
